### PR TITLE
Fixes typo in months

### PR DESCRIPTION
**Pull request by felipecespedes**
It fixes a typo in "septiembre"

### CODE REVIEW

**Comment by fferegrino** [comment]
¡Hey @felipecespedes! thanks for opening this PR 🎉 

Now, this is not a typo (at first I thought it was too!), as @diego-garro pointed out there are two spellings for that specific month 🙀 see here: https://dle.rae.es/setiembre and here https://es.wikipedia.org/wiki/Septiembre


What I propose is to move away from using a dict-comprehension to initialise the `MESES` variable and instead assign the months directly like:

```python
MESES = {
    'enero': 0,
    'febrero': 1,
# ...
```

Please let me know if this is something you'd like to do.

**Comment by felipecespedes** [comment]
@fferegrino didn't know that 🤯, thanks for clarifying. 
Even **octubre** has its variant **[otubre](https://dle.rae.es/otubre)**, I think the beauty of the open-source is that every day you can learn something new.

Regarding what you are asking for, does it mean that for *septiembre* it will have two entries in the dict, right?
```python
MESES = {
  # ...
  'septiembre': 8,
  'setiembre': 8
  # ...
}
```

**Comment by fferegrino** [comment]
Sorry for the delay on this,  @felipecespedes. For now, yeah, it seems the most reasonable solution to me.

**Comment by fferegrino** [comment]
Closed due inactivity.

**Pull request closed without merging**
